apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolioAuthentication-deployment
  labels:
    app: portfolio_Authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio_Authentication  
  template:
    metadata:
      labels:
        app: portfolio_Authentication
    spec:
      containers:
      - name: portfolioAuthentication
        image: myfirstregistryas.azurecr.io/authserviceimages:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsecret
---
apiVersion: v1
kind: Service
metadata:
  name: portfolioAuthentication
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: portfolio_Authentication
